services:

  rutx:
    build: .
    # image: ghcr.io/rise-maritime/keelson-connector-rutx:latest
    container_name: keelson-connector-rutx
    restart: unless-stopped
    network_mode: "host"
    command: "--log-level 10 -r rise -e landkrabban -s rutx --publish raw_string --publish raw --publish log --publish nmea --udp-port 8500"
    
