services:

  rutx:
    build: .
    # image: ghcr.io/rise-maritime/keelson-connector-rutx:latest
    container_name: keelson-connector-rutx
    restart: unless-stopped
    network_mode: "host"
    command: "main --help" # --log-level 10 -r rise -e landkrabban -s rutx  --publish raw --udp-port 8500"
    
