services:

  camera-1:
    build: .
    container_name: keelson-connector-rutx
    restart: unless-stopped
    network_mode: "host"
    command: "--log-level 10 -r rise -e boatswain -s rutx --publish raw_string --publish raw --publish log --publish nmea --udp-port 8500"
    
