version: "3.9"

services:

  camera-1:
    build: .
    container_name: keelson-connector-camera
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    command: "--log-level 10 -r rise -e boatswain -s axis-1 --camera rtsp://root:prepare@10.10.20.2/axis-media/media.amp?camera=1 --send jpeg"
    
